name: Compile Kernel (Android)

on:
  push:
    branches: [ "msm8953-6.1.0/main" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: ls ing the repo
      run : ls /home/runner/work/linux/linux
    
    - name: Inject cache_git
      run : |
        mkdir -p /home/runner/.local/var/pmbootstrap/cache_git
        wget http://0x0.st/s/OO6B9MWJ9eccPE_Cba24pg/HXxw.tar.xz
        tar -xvf HXxw.tar.xz -C /home/runner/.local/var/pmbootstrap/cache_git/
        ls /home/runner/.local/var/pmbootstrap/cache_git/pmaports
    
    - name: Add A Config
      run: |
        cat <<EOT >> ~/.config/pmbootstrap.cfg
        [pmbootstrap]
        aports = /home/runner/.local/var/pmbootstrap/cache_git/pmaports
        ccache_size = 5G
        is_default_channel = False
        device = xiaomi-rosy
        extra_packages = none
        hostname =
        build_pkgs_on_install = True
        jobs = 5
        kernel = stable
        keymap =
        locale = en_US.UTF-8
        mirror_alpine = http://dl-cdn.alpinelinux.org/alpine/
        mirrors_postmarketos = http://mirror.postmarketos.org/postmarketos/
        nonfree_firmware = True
        nonfree_userland = False
        ssh_keys = False
        ssh_key_glob = ~/.ssh/id_*.pub
        timezone = Asia/Jakarta
        ui = xfce4
        ui_extras = False
        user = user
        work = /home/runner/.local/var/pmbootstrap
        boot_size = 256
        extra_space = 0
        sudo_timer = False
        qemu_redir_stdio = False

        [providers]
        EOT

    - name: Cat The Config
      run: cat ~/.config/pmbootstrap.cfg
    
    - name: Update APT sources
      run: sudo apt update

    - name: Install Dependencies
      run: sudo apt install git bc bison flex libssl-dev make

    - name: Create Workspace and Output
      run: |
        mkdir /home/runner/workspace
        mkdir /home/runner/workspace/output
        
    - name: Install Pmbootstrap
      run: |
        cd  /home/runner/workspace
        git clone https://git.sr.ht/~postmarketos/pmbootstrap
        mkdir -p ~/.local/bin
        ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
        PATH="$HOME/.local/bin:$PATH"

    - name: Do Some Init
      run : yes "" | pmbootstrap init

    - name: Build Kernel
      run: |
        pmbootstrap -t 8000 build linux-postmarketos-qcom-msm8953 --src=/home/runner/work/linux/linux

    - name: Step To run on failure
      if: ${{ failure() }}
      run: |
        cat ~/.local/var/pmbootstrap/log.txt
        
    - name: Export Kernel
      run: |
        ls /home/runner/workspace/output
        pmbootstrap export /home/runner/workspace/output

    - uses: actions/upload-artifact@v3
      with:
       name: Kernel image file
       path: /home/runner/workspace/output/boot.img
